storage:
  endpoint: nil
  access_key_id: <%= ENV["STORAGE_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["STORAGE_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["STORAGE_REGION"] %>
  bucket: <%= ENV["STORAGE_BUCKET"] %>
  force_path_style: <%= ENV.fetch("STORAGE_FORCE_PATH_STYLE", "false") %>
